### ISSUE TITLE
Retrieve a PHLO Run

### ISSUE THREAD

**Issue by davidcmoody** [plivo/plivo-php#127]
Is there a way to retrieve a PHLO run with this API?

https://www.plivo.com/docs/phlo/api-reference/phlo/retrieve-a-phlo-run/

When I run a PHLO, I would like to save the Message UUID in my database, but the only way to get that message UUID is to retrieve the PHLO run?

It comes back in the PHLO->run "message" object, but it is not parsable.

**Comment by davidcmoody** [comment]
I created a function in Plivo/Resources/PHLO/Phlo.php that allows me to get the PHLO run information:
`
    /**
	 * @param phlo_id
	 * @param run_id
	 * @return mixed
	 */
	public function getPhloRun($phlo_id, $run_id)
	{
		$phlo = new self($this->client, $phlo_id, $this->baseUrl);
		$response = $phlo->client->getPhlorunner($phlo->phloUrl . '/runs/' . $run_id, []);
		return $response->getContent();
	}
`

**Comment by nixonsam** [comment]
@davidcmoody Thank you for the help!

We will work on this and update our library.

**Comment by huzaif-plivo** [comment]
@davidcmoody At the moment we request you to make use of an [endpoint](https://www.plivo.com/docs/phlo/api/phlo/#retrieve-a-phlo-run) to fetch the required detail such as message_uuid. Meanwhile, we are working on this as a feature request.

In case of any queries, please feel free to contact our [support team](https://support.plivo.com/hc/en-us).
