### ISSUE TITLE
Undefined Index 'restriction' v4.3.3

### ISSUE THREAD

**Issue by placeposition** [plivo/plivo-php#128]
```

$plivo_sms = new RestClient($plivo['auth_id'], $plivo['auth_token']);

$r = $plivo_sms->phonenumbers->list('GB');

```
This example taken directly from docs.

Undefined index: restriction in /vendor/plivo/plivo-php/src/Plivo/Resources/PhoneNumber/PhoneNumber.php</b> on line 51

Undefined index: restriction_text in /vendor/plivo/plivo-php/src/Plivo/Resources/PhoneNumber/PhoneNumber.php</b> on line 52

**Comment by nixonsam** [comment]
@placeposition we are looking into this. we will get back to you with an update shortly.

**Comment by nixonsam** [comment]
@placeposition Below code snippet is working fine.

<?php
/**
 * Example for PhoneNumber list
 */
require 'vendor/autoload.php';
use Plivo\RestClient;
use Plivo\Exceptions\PlivoRestException;
$client = new RestClient("YOUR_AUTH_ID", "YOUR_AUTH_TOKEN");

try {
    $response = $client->phonenumbers->list(
        'GB'
    );
    print_r($response);
}
catch (PlivoRestException $ex) {
    print_r(ex);
}

Please create a support ticket if you are still facing any issues.

**Comment by victoriafrench** [comment]
wow i actually stepped through the code and found the issue in your lib and here you are claiming there is no issue.

**Comment by placeposition** [comment]
@nixonsam - you can't possibly have checked the code you say is working fine- (ex) needs a $.

**Comment by nixonsam** [comment]
@placeposition we have checked this and found that this was happening to a few countries where the data for Restriction & RetrictionText was not sent from API server. This is fixed now. 

below Code snippet should work fine and should also help you to access the properties from the response object.

try {
        $response = $client->phonenumbers->list(
                                                'GB'
                                                );
        foreach($response->getIterator() as $a) {
            print_r($a->properties);
        }
    }
    catch (PlivoRestException $ex) {
        print_r($ex);
}
