### ISSUE TITLE
Not pulling sms numbers

### ISSUE THREAD

**Issue by victoriafrench** [plivo/plivo-php#129]
When attempting to pull sms numbers with the latest, nothing comes back.

```php
    $plivo_sms = new RestClient($plivo['auth_id'], $plivo['auth_token']);

    // returns 0 results
    $r = $plivo_sms->getPhoneNumbers()->getList('GB', array(
         "type" => "mobile",
         "limit" => 10,
         "offset" => 0
    ));

    // returns 0 results
    $r = $plivo_sms->getPhoneNumbers()->getList('GB', array(
         "services" => "sms",
         "limit" => 10,
         "offset" => 0
    ));

     // returns 0 results
    $r = $plivo_sms->getPhoneNumbers()->getList('GB', array(
         "type" => "mobile",
         "services" => "sms",
         "limit" => 10,
         "offset" => 0
    ));

    // returns 10 results all 800 numbers with smsEnabled: false
    $r = $plivo_sms->getPhoneNumbers()->getList('GB', array(
         "limit" => 10,
         "offset" => 0
    ));
```

This is on top of the error described in #128.

I have tried multiple locales to make sure it wasn't a number availability issue. GB, US, CA, MX, and others are all returning 0 items. Perhaps the error is causing this though, I am unsure.

**Comment by nixonsam** [comment]
@victoriafrench we are looking into this. we will get back to you with an update shortly.

**Comment by nixonsam** [comment]
@victoriafrench below code snippet works for me. Version of the SDK is 4.3.3(https://github.com/plivo/plivo-php/releases/tag/v4.3.3)

try {
    $response = $client->phonenumbers->list(
        'US',
        [
          "type" => "fixed",
          "services" => "sms"
        ]
    );
    print_r($response);
}
catch (PlivoRestException $ex) {
    print_r(ex);
}

**Comment by victoriafrench** [comment]
so mobile is dead is what you are saying?

**Comment by nixonsam** [comment]
@victoriafrench For different countries SMS enabled numbers are either available as mobile numbers or as fixed numbers. please contact support team, they would be able to help you accordingly.

**Comment by placeposition** [comment]
I swapped the 'US' for 'GB' and it fails

**Comment by nixonsam** [comment]
@placeposition this is because we do not have any SMS enabled numbers available for GB.

![Screenshot 2019-04-26 at 5 05 12 PM](https://user-images.githubusercontent.com/37671608/56805083-854da080-6845-11e9-86dd-87f10f77ebac.png)

Please contact our support team, they would be able to check and assist if they can acquire any SMS enabled numbers.
