### ISSUE TITLE
HTTP Error in Plivo_Confrence.php

### ISSUE THREAD

**Issue by ZeeshanTahammul** [plivo/plivo-php#13]
Hello,
i don't know why i am getting this error on my localhost pc

Fatal error: Uncaught <table style="border: 1px" cellspacing="0"> <tr><td colspan="3" style="background: #ff9999"> <b>HTTP_Request2_MessageException</b>: Curl error: Received HTTP code 302 from proxy after CONNECT in <b>D:\xampp\htdocs\plivo\HTTP\Request2\Adapter\Curl.php</b> on line <b>177</b></td></tr> <tr><td colspan="3" style="background-color: #aaaaaa; text-align: center; font-weight: bold;">Exception trace</td></tr> <tr><td style="text-align: center; background: #cccccc; width:20px; font-weight: bold;">#</td><td style="text-align: center; background: #cccccc; font-weight: bold;">Function</td><td style="text-align: center; background: #cccccc; font-weight: bold;">Location</td></tr> <tr><td style="text-align: center;">0</td><td>HTTP_Request2_Adapter_Curl::wrapCurlError('Resource id #10')</td><td>D:\xampp\htdocs\plivo\HTTP\Request2\Adapter\Curl.php:177</td></tr> <tr><td style="text-align: center;">1</td><td>HTTP_Request2_Adapter_Curl->sendRequest(Object(HTTP_Request2))</td><td>D:\xampp\htdocs\plivo\HTTP\Request2.php:93 in D:\xampp\htdocs\plivo\HTTP\Request2\Adapter\Curl.php on line 149

**Comment by sandeepraju** [comment]
HTTP_Request2 is removed in the next release. You can update the helper and try again when it is released.
