### ISSUE TITLE
X-Plivo-Signature-V2 and X-Plivo-Signature-V2-Nonce

### ISSUE THREAD

**Issue by apexapexapex** [plivo/plivo-php#130]
`X-Plivo-Signature-V2` and `X-Plivo-Signature-V2-Nonce` are not passed to the `answer_url`.

I checked for `$_SERVER['HTTP_X-Plivo-Signature-V2']` and `$_SERVER['HTTP_X-Plivo-Signature-V2-Nonce']`. I even double checked using `getallheaders()`.

I want to validate that the request is coming from Plivo before returning any sensitive data.

Please advise.

**Comment by nixonsam** [comment]
@apexapexapex we are looking into this, we will keep you posted with an update shortly.

**Comment by apexapexapex** [comment]
@nixonsam any updates on this? Sorry, we are pushing our IVR system to QA soon.

**Comment by nixonsam** [comment]
@apexapexapex You can access the Signature, Nonce, & MA_V2 like below

$signature_v2 = $_SERVER['HTTP_X_PLIVO_SIGNATURE_V2'];
$signature_v2_nonce = $_SERVER['HTTP_X_PLIVO_SIGNATURE_V2_NONCE'];
$signature_ma_v2 = $_SERVER['HTTP_X_PLIVO_SIGNATURE_MA_V2'];

Please feel free to create a support ticket if you need any further assistance or in case of any issues.
Thank you!
