### ISSUE TITLE
undefined index restriction

### ISSUE THREAD

**Issue by mkhrystunov** [plivo/plivo-php#132]
Here's the snippet from `Plivo\Resources\PhoneNumber\PhoneNumber::__construct`:
![image](https://user-images.githubusercontent.com/5919578/57810752-35da0080-7771-11e9-8faf-cf9a6f665405.png)

The problem is that there is no restriction and restrictionText in response:
![image](https://user-images.githubusercontent.com/5919578/57810675-07f4bc00-7771-11e9-8e4d-2b85dd53a30c.png)

**Comment by nixonsam** [comment]
@mkhrystunov Thank you for bringing this up! 
we are getting this fixed. Will publish a new version after this is fixed.

**Comment by mkhrystunov** [comment]
hey @nixonsam ,
when is this issue expected to be fixed?

**Comment by nixonsam** [comment]
@mkhrystunov  we have checked this and found that this was happening to a few countries where the data for Restriction & RetrictionText was not sent from API server. This is fixed now. 

below Code snippet should work fine and should also help you to access the properties from the response object.

try {
        $response = $client->phonenumbers->list(
                                                'GB'
                                                );
        foreach($response->getIterator() as $a) {
            print_r($a->properties);
        }
    }
    catch (PlivoRestException $ex) {
        print_r($ex);
}

**Comment by mkhrystunov** [comment]
thanks, this works now
