### ISSUE TITLE
bug in delete number response

### ISSUE THREAD

**Issue by loaicoperato** [plivo/plivo-php#133]
in file  src/Plivo/Resources/Number/NumberInterface.php at line 147 
the delete function is not returnning the instanse of the client object

**Comment by loki-NK** [comment]
@loaicoperato We will be looking into this.

**Comment by huzaif-plivo** [comment]
@loaicoperato In most instances, Plivo doesn't return any response to any DELETE requests & the Delete number, makes use of the DELETE method/DELETE request. Hence there wasn't an instance returned. You can also view our [API docs](https://www.plivo.com/docs/numbers/api/account-phone-number#unrent-a-number) for the request method and response we have for the APIs.

In case if there is anything else, please feel free to contact our [support team](https://support.plivo.com/hc/en-us).
