### ISSUE TITLE
Error in Plivo Application undefined index "log_incoming_messages" 

### ISSUE THREAD

**Issue by ghost** [plivo/plivo-php#135]
There is an error coming from Plivo lib core files. The error is in constructor of Application Class. where $properties variable is constructed from response. Error is undefined index ["log_incoming_messages"]. Originally the response contains singular while in lib its accessed as plural with. The error is resolved by removing `s` from ["log_incoming_messages"] to ["log_incoming_message"]. now the lines looking as 

'logIncomingMessages' => $response['log_incoming_messages']   x
'logIncomingMessages' => $response['log_incoming_message']    👍

**Comment by alanzhaonys** [comment]
Encounter this issue as well. Please provide update. Thanks

**Comment by huzaif-plivo** [comment]
@alanzhaonys This has been fixed and deployed in our latest release [v4.16.0](https://github.com/plivo/plivo-php/releases/tag/v4.16.0).
