### ISSUE TITLE
Make plivo installable via Composer

### ISSUE THREAD

**Issue by deplorableword** [plivo/plivo-php#14]
Would be great if I could install this via Composer.

Note; If anyone wants to submit a PR to do this, the http_request2 lib is alreday available on packagist https://packagist.org/packages/pear/http_request2

**Comment by radutopala** [comment]
:+1: ping anyone?

**Comment by deplorableword** [comment]
if anyone does fancy doing this, please also changes in #4 and #8. Only way I could get this lib to run with Laravel

**Comment by radutopala** [comment]
Have a look at https://packagist.org/packages/radutopala/plivo-php

**Comment by deplorableword** [comment]
Amazing. Could you create a PR so @tamiel can merge this in?

**Comment by radutopala** [comment]
Is @tamiel interested? Seems like all those PRs already open are hanging there..

**Comment by radutopala** [comment]
In `composer.json` you can already use `"radutopala/plivo-php": "dev-master"`, if you want.

**Comment by sandeepraju** [comment]
@radutopala @deplorableword we are reviewing all pending issues and PRs.. We'll close this by early next week. Thanks for your contributions.

**Comment by deplorableword** [comment]
@sandeepraju thanks. Having a PHP package in 2015, means having a composer compatible project.

**Comment by sandeepraju** [comment]
@radutopala @deplorableword I have made all the changes in the [dev branch](https://github.com/plivo/plivo-php/tree/dev). Can you give it a spin when you find time? I'll merge it to master early next week.

@radutopala your changes have been added to the same branch :)

**Comment by radutopala** [comment]
@sandeepraju pls also add the repo to packagist, when you have the chance.

**Comment by nebkam** [comment]
:+1:

**Comment by chrisgo** [comment]
Hi, please update dependency on guzzle/guzzle (deprecated) to guzzlehttp/guzzle (https://packagist.org/packages/guzzlehttp/guzzle)

**Comment by sandeepraju** [comment]
@chrisgo I am retaining guzzle/guzzle for now as it requires a lower version of PHP (5.3) than the latest guzzle (which requires 5.4) as many of our users may face issues with the higher version requirement. Unless there are any serious bottlenecks with the current version, i'd refrain from upgrading to the latest version of guzzle.

**Comment by chrisgo** [comment]
@sandeepraju: got it

**Comment by amalfra** [comment]
Any ETA?

**Comment by cachrisman** [comment]
https://packagist.org/packages/plivo/plivo-php
