### ISSUE TITLE
Notice: Undefined index: invalid_number in C:\xampp\htdocs\alooviv2\vendor\plivo\plivo-php\src\Plivo\Resources\Message\MessageInterface.php on line 184

### ISSUE THREAD

**Issue by kiranbhattarai** [plivo/plivo-php#143]
I am using plivo version 4.3 with php 7.1
I get the sms but i also get the notice. 

`Notice: Undefined index: invalid_number in C:\xampp\htdocs\alooviv2\vendor\plivo\plivo-php\src\Plivo\Resources\Message\MessageInterface.php on line 184`

**Comment by loki-NK** [comment]
Hello Kiran,

Can you help me with the API ID returned when the message is sent?

**Comment by brightjune** [comment]
Hi,

I got the same error.

Plivo Version: v4.3.4
PHP 7.3.1

**Comment by kiranbhattarai** [comment]
> Hello Kiran,
> 
> Can you help me with the API ID returned when the message is sent?
  api_id : 83cce84a-b7a7-11e9-8b49-0242ac110004
I downgraded to version 4.0 immediately after the error.  And the error was resolved.

**Comment by kiranbhattarai** [comment]
> Hi,
> 
> I got the same error.
> 
> Plivo Version: v4.3.4
> PHP 7.3.1

STEP 1: Try add 1 in front of your 10 digit number for example: 14445552525 
STEP 2: Try add +1 in front of your 10 digit number for example: +14445552525 
STEP 3: Downgrade to version 4.0

**Comment by brightjune** [comment]
@kiranbhattarai 
Yeah, Downgrade to version 4.1 is ok.

Thank you!

**Comment by drewjoh** [comment]
I have the same issue and have downgraded and locked composer to v4.3.3.

**Comment by artembeloglazov** [comment]
Should me expect a task to close? I have got the same error.

**Comment by kenpingshu** [comment]
I have same issue when use v4.3.5
I think is because of when the request doesn't has invalid number, 
that will not have invalid number  key in response body array, 
need to check is key exist or not on MessageInterface.php line 184

**Comment by cdrum** [comment]
same issue here with 4.3.4.

**Comment by mdb983** [comment]
Same issue on 4.3.4. Downgraded to 4.3.3 and all works fine. After 2 months I would have thought you would have pulled the build or fixed the issue. Shocking!!!!

**Comment by kocheski-d** [comment]
> Same issue on 4.3.4. Downgraded to 4.3.3 and all works fine. After 2 months I would have thought you would have pulled the build or fixed the issue. Shocking!!!!

Go to MessageInterface.php

slide down to create function ~ 178 line 

change this:

$responseContents['message'],
                $responseContents['message_uuid'],
                $responseContents['api_id'],
                $response->getStatusCode(),
                $responseContents['invalid_number']

to this:

$responseContents['message'],
                $responseContents['message_uuid'],
                $responseContents['api_id'],
                $response->getStatusCode(),
                isset($responseContents['invalid_number']) ? $responseContents['invalid_number'] : ''

if there is no invalid number, the API doesnt return invalid_number key, but the MessageCreateResponse expects invalid_number

**Comment by obscurecloud** [comment]
I suggest (in PR https://github.com/plivo/plivo-php/pull/153) to change the line @kocheski-d referred to to:
`array_key_exists('invalid_number', $responseContents) ? $responseContents['invalid_number'] : []`
since the `MessageCreateResponse` constructor looks for an explicit `[]` 
/src/Plivo/Resources/Message/MessageCreateResponse.php:25

**Comment by huzaif-plivo** [comment]
The issue isn’t reproducible in the latest version [v4.15.1](https://github.com/plivo/plivo-php/releases/tag/v4.15.1). Therefore we request you to retry. Feel free to contact the [support team](https://support.plivo.com/hc/en-us) for any concerns.
