### ISSUE TITLE
search_numbers from RestAPI

### ISSUE THREAD

**Issue by thiaramus** [plivo/plivo-php#15]
Method "search_numbers" in RestAPI calls up for AvailableNumber URL part, while by Plivo API docs it should be "PhoneNumber". So this method does not work as it should.

**Comment by sandeepraju** [comment]
@thiaramus to use the `PhoneNumber` API, please use the `search_phone_numbers ` function.

`search_numbers` function will be phased out over time and hence it is not recommended to use it.
