### ISSUE TITLE
Plivo\Exceptions\PlivoResponseException text parameter not present

### ISSUE THREAD

**Issue by qas1** [plivo/plivo-php#158]
```
Plivo\Exceptions\PlivoResponseException text parameter not present
```
```
Plivo\Resources\Message\MessageInterface::create :201
...\vendor\plivo\plivo-php\src\Plivo\Resources\Message\MessageInterface.php:201
```

Error occurs when attempting to send an SMS using the example provided here -  https://github.com/plivo/plivo-php#send-a-message

Occurs on v4.3.8 (latest at the time of writing). It does not occur on 4.3.7.

**Comment by richardksizemore** [comment]
Same issue here downgrading to 4.3.7 until addressed

Laravel Framework 5.8
PHP 7.2.25

**Comment by Divyesh-mi** [comment]
> Same issue here downgrading to 4.3.7 until addressed
> 
> Laravel Framework 5.8
> PHP 7.2.25

It's working after downgrading to 4.3.1

**Comment by gustavosobrinho01** [comment]
I created a PR solving this problem in code: https://github.com/plivo/plivo-php/pull/161

**Comment by huzaif-plivo** [comment]
@gustavosobrinho01 @qas1 @richardksizemore The issue isn’t reproducible in the latest version [v4.15.1](https://github.com/plivo/plivo-php/releases/tag/v4.15.1). Therefore we request you to retry. Feel free to contact the [support team](https://support.plivo.com/hc/en-us) for any concerns.
