### ISSUE TITLE
PHP Error[8]: Undefined index: from_number

### ISSUE THREAD

**Issue by kangaroodev** [plivo/plivo-php#168]
PHP 7.0
Plivo PHP SDK: v4.4.1

```
$client = new \Plivo\RestClient('KEY', 'SECRET');
$response = $client->messages->get('SOME_ID');
```

```
PHP Error[8]: Undefined index: from_number
    in file /var/www/html/protected/vendor/plivo/php-sdk/src/Plivo/Resources/Message/Message.php at line 38
#0 /var/www/html/protected/vendor/plivo/php-sdk/src/Plivo/Resources/Message/MessageInterface.php(53): Plivo\Resources\Message\Message->__construct()
#1 /var/www/html/protected/models/Test.php(3873): Plivo\Resources\Message\MessageInterface->get()
```

The Error is on line 38 in
vendor/plivo/php-sdk/src/Plivo/Resources/Message/Message.php

```
public function __construct(
        BaseClient $client, $response, $authId)
    {
        parent::__construct($client);

        $this->properties = [
            'from' => $response['from_number'],
            'to' => $response['to_number'],
            'messageDirection' => $response['message_direction'],
            'messageState' => $response['message_state'],
            'messageTime' => $response['message_time'],
            'messageType' => $response['message_type'],
            'messageUuid' => $response['message_uuid'],
            'resourceUri' => $response['resource_uri'],
            'totalAmount' => $response['total_amount'],
            'totalRate' => $response['total_rate'],
            'units' => $response['units']
        ];

        $this->pathParams = [
            'authId' => $authId,
            'messageUuid' => $response['message_uuid']
        ];

        $this->id = $response['message_uuid'];
    }
```

**Comment by ceswebmaster** [comment]
Still an issue in 4.9

**Comment by ceswebmaster** [comment]
If it helps, I had this error then it appeared that the UUID I was using was related to a voice call, not a text message.

**Comment by ceswebmaster** [comment]
Everything was working OK up until last week and now I'm getting this same issue again with both Voice and Message ->get requests. I updated the package today in hopes recent changes fixed it but none. If I dump the response before it is assigned to properties, the error is:

**CDR for call uuid XXXX**

**Comment by ceswebmaster** [comment]
OK.. Interesting enough I think this isn't a code error, this is a Plivo error. They don't appear to hold any logs prior to 3 months (just from looking at their filter option and with debugging messages/calls sent out back in the beginning of June). So this is where the error was coming in for me as I am trying to allow reports for older information.

**Comment by narayana-plivo** [comment]
@ceswebmaster  @kangaroodev  Here is the PR for same : https://github.com/plivo/plivo-php/pull/193

**Comment by nixonsam** [comment]
This is released, check release https://github.com/plivo/plivo-php/releases/tag/v4.13.0
@ceswebmaster @kangaroodev
