### ISSUE TITLE
Use namespace and/or add prefix 

### ISSUE THREAD

**Issue by kostiag** [plivo/plivo-php#18]
User, Element, Response etc. are very common class names that are more likely to be named as such in the application so importing plivo would conflict IMHO

**Comment by blockjon** [comment]
Agreed. This PHP package is not able to be used in almost any project due to the fact the class names will collide with other similar class names in the global namespace.

**Comment by tsudot** [comment]
You should check out the dev branch - https://github.com/plivo/plivo-php/tree/dev

**Comment by cachrisman** [comment]
the current release has a namespace, Plivo.
