### ISSUE TITLE
Guzzle 7 Support

### ISSUE THREAD

**Issue by elijahchancey** [plivo/plivo-php#188]
We're trying to upgrade to Laravel 8, which depends on Guzzle 7. This package only supports up to Guzzle 6. Please add Guzzle 7 support. Thanks!

**Comment by uisumo** [comment]
Yes we are also on same need.

**Comment by senaranya** [comment]
Same here! This is the only package we're waiting on to move to Guzzle-7 before we can upgrade Laravel to v8.

**Comment by jab1000** [comment]
Agreed need Guzzle 7 Support.  Thanks!

**Comment by cdrum** [comment]
same here pleeeeaase?? ;-)

**Comment by narayana-plivo** [comment]
released

**Comment by cdrum** [comment]
> released

You guys rock thanks!

**Comment by nixonsam** [comment]
This is fixed, check release https://github.com/plivo/plivo-php/releases/tag/v4.13.0
@jab1000 @senaranya @uisumo @elijahchancey
