### ISSUE TITLE
Phlo Call Forwarding

### ISSUE THREAD

**Issue by sajeenake** [plivo/plivo-php#219]
Hi

Is it possible to make the call forwarding numbers to sales and support dynamic payload, I need to have it fetch from an API which I created ?

**Comment by huzaif-plivo** [comment]
@sajeenake If my interpretation is right, you'd want to make an HTTP request to your API before executing the [Call forward node](https://www.plivo.com/docs/phlo/components#call-forward) to obtain the phone numbers to be forwarded.

In that case, the [HTTP node](https://www.plivo.com/docs/phlo/components#http-request) can then be used. The response received can be accessed within [Call forward node](https://www.plivo.com/docs/phlo/components#call-forward). If you require any further assistance, please contact our support team.
