### ISSUE TITLE
Plivo is phasing out /AvailableNumber and /Number need to upgrade to /PhoneNumber

### ISSUE THREAD

**Issue by lancerushing** [plivo/plivo-php#22]
@see https://www.plivo.com/blog/improved-phone-number-inventory-search/

Methods search_numbers() and get_number() need to be updated.

**Comment by cachrisman** [comment]
[search_phone_numbers](https://github.com/plivo/plivo-php/blob/master/plivo.php#L193) and [buy_phone_number](https://github.com/plivo/plivo-php/blob/master/plivo.php#L197) are the updated functions for searching and buying phone numbers.
