### ISSUE TITLE
guzzlehttp/guzzle v3.8.1 ?

### ISSUE THREAD

**Issue by elburro1887** [plivo/plivo-php#24]
Why are you "hard"-setting such an old version of guzzle? It's at v6.x right now. 
A lot of other libs depend on guzzle also, and the plivo lib is unnecessarily limiting this version.

**Comment by SvenRtbg** [comment]
The guzzle version 3 is independent of the later versions because the package was renamed. However, you are right that using an old, unmaintained, not-the-latest version isn't the best idea.

**Comment by cachrisman** [comment]
we are working on changing the code to use the latest version of guzzle, but the current version works unless your code or other dependencies require a newer version. If anyone wants to help, please submit a PR.

**Comment by cachrisman** [comment]
Just published a new release using guzzle 6.1.1. Please check out and let us know if there are any problems.

**Comment by elburro1887** [comment]
great. thanks!
