### ISSUE TITLE
plivo-php locked to an older version of firebase/php-jwt

### ISSUE THREAD

**Issue by erangalp** [plivo/plivo-php#254]
When trying to update the firebase/php-jwt to its latest version (6.0), composer is running into a conflict with the plivo-php which is locked into the previous version (5.x+)

    - plivo/plivo-php is locked to version v4.25.1 and an update of this package was not requested.
    - plivo/plivo-php v4.25.1 requires firebase/php-jwt ^5.2 -> found firebase/php-jwt[v5.2.0, ..., v5.5.1] but it conflicts with your root composer.json require (^6.0).

This prevents us from using the latest version of firebase/php-jwt which contains additional encryption options and some bug fixes. Would appreciate updating the dependency requirements here.

**Comment by huzaif-plivo** [comment]
@erangalp Thank you for the feedback! We have fixed this in our [latest release](https://github.com/plivo/plivo-php/releases/edit/v4.27.0) Feel free to contact our [support team](https://support.plivo.com/hc/en-us) for any queries.
