### ISSUE TITLE
error on listing numbers

### ISSUE THREAD

**Issue by jab1000** [plivo/plivo-php#278]
I keep throwing an error on this and have for quite some time.   Doesn't look like any of my code is throwing the error though directly...

I also simplified my code to down to be just this... still same error.
```
$client = new RestClient('yyyy', 'xxxxx');
$response = $client->numbers->list(['limit'=>20, 'offset'=>0]);
```
and also tried this assuming the defaults should work:
```
$client = new RestClient('yyyy', 'xxxxx');
$response = $client->numbers->list();
```

Here is the error stack trace - thoughts?
PHP 8.0.x
latest plivo php
running in laravel V8
FYI, sending sms messages works without issues.

[2022-09-06 14:58:17] production.ERROR: Undefined array key "object_id" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"object_id\" at /var/www/vendor/plivo/plivo-php/src/Plivo/Resources/Number/Number.php:75)
[stacktrace]
#0 /var/www/vendor/plivo/plivo-php/src/Plivo/Resources/Number/Number.php(75): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/vendor/plivo/plivo-php/src/Plivo/Resources/Number/NumberInterface.php(66): Plivo\\Resources\\Number\\Number->__construct()
#2 [internal function]: Plivo\\Resources\\Number\\NumberInterface->getList()
#3 /var/www/vendor/plivo/plivo-php/src/Plivo/Resources/ResourceInterface.php(65): call_user_func_array()
#4 /var/www/app/Models/PersonSmsNumber.php(176): Plivo\\Resources\\ResourceInterface->__call()

[2022-09-06 14:48:58] production.ERROR: Undefined array key "object_id" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"object_id\" at /var/www/vendor/plivo/plivo-php/src/Plivo/Resources/Number/Number.php:75)

**Comment by huzaif-plivo** [comment]
@jab1000 We tried the list phone numbers API in the PHP SDK version 4.25.0 with PHP version 8.0.23, both with and without any parameters, however we were unable to reproduce the issue, and the API returned valid results in both situations. I recommend that you contact our [support-team](https://support.plivo.com/hc/en-us) to fix the issue.
