### ISSUE TITLE
Add PHP 8.1 support

### ISSUE THREAD

**Issue by toannguyendts** [plivo/plivo-php#285]
We have found some error when using on PHP 8.1

1/ Return type of Plivo\Resources\ResourceList::getIterator() should either be 
compatible with IteratorAggregate::getIterator(): Traversable
2/ Exception Message in PHP8.1:
http_build_query(): Passing null to parameter 2 ($numeric_prefix) of type string is deprecated

**Comment by narayana-plivo** [comment]
@toannguyendts we added support 8.1 on v4.37.1

@abhineet-plivo
