### ISSUE TITLE
Bypass SSL certificate verification with GuzzleHttp 6.x

### ISSUE THREAD

**Issue by simokhalil** [plivo/plivo-php#30]
Hi there,

Just a little workaround for those having the issue of the Error 60 regarding SSL certificate verification failure, when using `send_message()` function since updated Plivo to v1.1.0 making use of GuzzleHttp 6.1, and want to avoid SSL cert verification (ie : for local testing purpose)

I run into this issue today after updating my dev environment to the latest version of plivo and GuzzleHttp to 6.1.

I dont know if this can be implemented by plivo PHP team in a future release (by asking for a PR ?), but in case, I'm sharing it here...

So, at the begining of plivo.php (vendor/plivo/plivo.php if installed via composer), find this code : 

```PHP
private function request($method, $path, $params = array()) {
    $url = $this->api.rtrim($path, '/').'/';

    $client = new Client([
        'base_uri' => $url,
        'auth' => [$this->auth_id, $this->auth_token],
        'http_errors' => false
    ]);
    ...
```
and add support of optional "verify" parameter (defaults to true), like this :
```PHP
private function request($method, $path, $params = array(), $sslVerif = true) {
    $url = $this->api.rtrim($path, '/').'/';

    $client = new Client([
        'base_uri' => $url,
        'auth' => [$this->auth_id, $this->auth_token],
        'http_errors' => false,
        'verify' => $sslVerif
    ]);
    ...
```

then, still in plivo.php file, modify the `send_message()` function to accept and handle the new optional `$sslVerif` parameter, as follows:
```PHP
public function send_message($params = array(), $sslVerif = true) {
    return $this->request('POST', '/Message/', $params, $sslVerif);
}
```

From now, in your controller, if you want to avoid SSL certificate verification, you can add `false` parameter to `send_message()` call, like this:
```PHP
$plivoAPI->send_message($params, false);
```
or keep verification active by either setting the parameter to `true`, or by just not sending it : 
```PHP
$plivoAPI->send_message($params, true); 
// or $plivoAPI->send_message($params);
//These two calls will work the same way as we put default value of $verify to true
```

You should keep in mind that modifying the lib is definitely not a "best practice", as you will lose your changes if you update or reinstall the lib. That's why I'm asking Plivo team if it would be possible to implement it in a future release.

Regards.
Khalil

**Comment by keradus** [comment]
IMO it should not be in `request` and `send_message` method prototypes.
Bypassing SSL cert should be done only on some rare cases and it's most likely problem with env rather than one specific request. For that reason I would suggest to have it as property instead of method parameter.
Of course only if you decided to go allow to turn it off.

**Comment by cachrisman** [comment]
what are those rare cases? I don't understand when and where this is useful.

**Comment by cachrisman** [comment]
Looking into this a bit more, seems this is useful if your development machine doesn't have the proper ssl certificates installed correctly. You should download and correctly install the proper ssl certificates to get guzzle to work properly. Is that the gist of it? Are there other situations where this would be useful?

**Comment by cachrisman** [comment]
Please take a look at the [Common Errors](https://github.com/plivo/plivo-php/wiki/Common-Errors) page on the wiki for details regarding installing the correct SSL certificate bundle.
