### ISSUE TITLE
Object Id issue

### ISSUE THREAD

**Issue by shoaibafzal1** [plivo/plivo-php#308]
same error as this https://github.com/plivo/plivo-php/issues/278 for list numbers

vendor/plivo/plivo-php/src/Plivo/Resources/Number/Number.php
Undefined index: object_id and object_type while getting number list
if ($response['object_id']) {
            $this->properties['objectId'] =  $response['object_id'];
        }
        if ($response['object_type']) {
            $this->properties['objectType'] =  $response['object_type'];
        }
        
   shouldn't these vars i-e object_id or object_type should be checked I mean in_array($response, 'object_id') etc

**Comment by kalyan-plivo** [comment]
hi @shoaibafzal1,

We have fixed this in our [latest release](https://github.com/plivo/plivo-php/releases/tag/v4.44.2). Feel free to contact our [support team](https://support.plivo.com/hc/en-us) for any queries.
