### ISSUE TITLE
cannot create Profile die to error message

### ISSUE THREAD

**Issue by obouallam** [plivo/plivo-php#334]
Hello, i can't create a profile using plivo php sdk version 4.59, here's my test code :

`
         $client = new RestClient(
            env('PLIVO_AUTH_ID', ''),
            env('PLIVO_AUTH_TOKEN', '')
        );

        $client
        ->client
        ->setTimeout(60);
        $authorized_contact = array(
            "first_name" => "John",
            "last_name" => "Doe",
            "email" => "********@gmail.com",
            "title" => "Mr",
            "seniority" => "admin",
            "phone" => "9381590950"
        );
        $address = array(
            "street" => "660 Broadway",
            "city" => "New York City",
            "state" => "NY",
            "postal_code" => "10001",
            "country" => "US"
        );
        $res = $client
        ->profile
        ->create("vishnu104", "", "DIRECT", "GOVERNMENT", "ABC Inc", "111111111", "PROFESSIONAL", "US", "ABC", "NASDAQ", "NONE", "google.com", $address, $authorized_contact);
`

i got this response, the email is valid and exists and i've try with another emails but the response is the same :

`
{
    "api_id": "25e709a3-d0b9-4568-99a7-0fbc327bcfe2",
    "error": "Invalid request parameter(s) - email"
}
`

**Comment by narayana-plivo** [comment]
@obouallam We only accept valid work emails; emails from personal domains are not permitted.

**Comment by obouallam** [comment]
> @obouallam We only accept valid work emails; emails from personal domains are not permitted.

yes i have tried with my work email : ********@v12software.com, but the same response i got

**Comment by obouallam** [comment]
@narayana-plivo I think this issue belongs to a server error or something like that, i tried using curl the same message i got, i made sure to use a valid work email, here's my example using curl :

`
curl -X POST 'https://api.plivo.com/v1/Account/$AUTH_ID/Profile/' \
-u '$AUTH_ID:$AUTH_TOKEN' \
-H "Content-Type: application/json" \
-d '{
    "profile_alias" : "toto",
    "plivo_subaccount" : "",
    "customer_type" : "RESELLER",
    "entity_type" : "INDIVIDUAL",
    "company_name" : "xxxxxxxx",
    "ein" : "",
    "vertical" : "PROFESSIONAL",
    "ein_issuing_country" : "",
    "stock_symbol" : "",
    "stock_exchange" : "",
    "website" : "xxxxxxxxxx.com",
    "alt_business_id_type" : "",
    "authorized_contact" : {
        "email" : "bouallam@xxxxxxxx.com",
        "first_name" : "omar",
        "last_name" : "boualla",
        "title" :"Mr",
        "seniority" : "OTHER",
        "phone" : "1XXXXXXXXXX"
    },
    "address" : {
        "street" : "660 Broadway",
        "city" : "New York City",
        "state" : "NY",
        "postal_code" : "10001",
        "country" : "US"
    }
}';`

**Comment by narayana-plivo** [comment]
@obouallam Have you previously attempted to create a profile using a proxy server or VPN?

**Comment by obouallam** [comment]
@narayana-plivo No I am trying to create a profile just from the localhost server
