### ISSUE TITLE
Caught exception: Curl failed with error Failed to connect to 127.0.0.1: Permission denied 

### ISSUE THREAD

**Issue by udy786** [plivo/plivo-php#35]
Hi,

I have installed Plivo on Centos with Freeswithch 1.4.26. When I am using example-call.php from web server then its showing error "Caught exception: Curl failed with error Failed to connect to 127.0.0.1: Permission denied " but when I am running directly on command then call i going to Freeswitch withour any error. I am running command like "php example-call.php".

Please guide me. Is anything I am missing? 

Thanks
Uday.

**Comment by cachrisman** [comment]
You should send an email to support@plivo.com and they can help you figure out the issue. If you have a specific question regarding the plivo-php helper library, please reply directly here.
