### ISSUE TITLE
Porblem, SMS with purchased number .

### ISSUE THREAD

**Issue by supportclik** [plivo/plivo-php#55]
$client = new RestClient("xxxxx", "xxxx");
        $message_created = $client->messages->create(
            'purchased number', <---
            [$number],
    $message !== null ? $message . $digits : "Sem mensagem"
);

Does not display number purchased when sms arrives at destination.

**Comment by plivo-sdks** [comment]
@supportclik This doesn't seem like an issue with the SDK. 

Please contact our Support team (support.plivo.com) with the message UUID to investigate this further.
