### ISSUE TITLE
Issue with API response

### ISSUE THREAD

**Issue by renaudoq** [plivo/plivo-php#58]
I installed Plivo PHP SDK using Composer and the requests are exectued correctly but the response from the API is really strange (see below). Works perfectly with CURL though.

Did this happen to someone else by any chance?

Code:
`require 'composer/vendor/autoload.php';
use Plivo\RestClient;
$client = new RestClient("XXX", "YYY");
try {
    $response = $client->numbers->list();
    var_dump($response);
}
catch (PlivoRestException $ex) {
//    print_r(ex);
}`

Response:
`object(Plivo\Resources\ResourceList)#36 (5) { ["client":protected]=> object(Plivo\BaseClient)#2 (3) { ["timeout":protected]=> NULL ["httpClientHandler":protected]=> object(Plivo\HttpClients\PlivoGuzzleHttpClient)#5 (3) { ["guzzleClient":protected]=> object(GuzzleHttp\Client)#6 (1) { ["config":"GuzzleHttp\Client":private]=> array(7) { ["handler"]=> object(GuzzleHttp\HandlerStack)#7 (3) { ["handler":"GuzzleHttp\HandlerStack":private]=> object(Closure)#14 (2) { ["static"]=> array(2) { ["default"]=> object(Closure)#12 (2) { ["static"]=> array(2) { ["default"]=> object(GuzzleHttp\Handler\CurlMultiHandler)#8 (5) { ["factory":"GuzzleHttp\Handler\CurlMultiHandler":private]=> object(GuzzleHttp\Handler\CurlFactory)#9 (2) { ["handles":"GuzzleHttp\Handler\CurlFactory":private]=> array(0) { } ["maxHandles":"GuzzleHttp\Handler\CurlFactory":private]=> int(50) } ["selectTimeout":"GuzzleHttp\Handler\CurlMultiHandler":private]=> int(1) ["active":"GuzzleHttp\Handler\CurlMultiHandler":private]=> NULL ["handles":"GuzzleHttp\Handler\CurlMultiHandler":private]=> array(0) { } ["delays":"GuzzleHttp\Handler\CurlMultiHandler":private]=> array(0) { } } ["sync"]=> object(GuzzleHttp\Handler\CurlHandler)#10 (1) { ["factory":"GuzzleHttp\Handler\CurlHandler":private]=> object(GuzzleHttp\Handler\CurlFactory)#11 (2) { ["handles":"GuzzleHttp\Handler\CurlFactory":private]=> array(1) { [0]=> resource(49) of type (curl) } ["maxHandles":"GuzzleHttp\Handler\CurlFactory":private]=> int(3) } } } ["parameter"]=> array(2) { ["$request"]=> string(10) "" ["$options"]=> string(10) "" } } ["streaming"]=> object(GuzzleHttp\Handler\StreamHandler)#13 (1) { ["lastHeaders":"GuzzleHttp\Handler\StreamHandler":private]=> array(0) { } } } ["parameter"]=> array(2) { ["$request"]=> string(10) "" ["$options"]=> string(10) "" } } ["stack":"GuzzleHttp\HandlerStack":private]=> array(4)`
and it keeps going...

**Comment by chhedadhaval120386** [comment]
DId you download the file or you did a composer install ? If you downloaded the file and did not do a composer dump-autoload then the autoload file will not be updated and composer will have no idea of these new namespaces and hence the issue.

**Comment by nixonsam** [comment]
@renaudoq we are closing this issue, feel free to reach out to our support team if you need any assistance.
