### ISSUE TITLE
Send message response missing api_id

### ISSUE THREAD

**Issue by alecjamesgarcia** [plivo/plivo-php#59]
The MessageCreateResponse Class and MessageInterface Class does not pass back "api_id" even though it is available in the $responseContents variable in MessageInterface->create() function. Also I did not see a way to get the response code anymore.

**Comment by nixonsam** [comment]
@alecjamesgarcia this is fixed in the recent release(https://github.com/plivo/plivo-php/releases/tag/v4.1.0), closing this issue. Feel free to contact our support if you need any further help.
