### ISSUE TITLE
How can i get the messageUuid value . I want to get this value 33f02d5e-56d8-11e8-8464-02f0efebfcdc

### ISSUE THREAD

**Issue by algobasket** [plivo/plivo-php#60]
object(Plivo\Resources\Message\MessageCreateResponse)#53 (2) { ["messageUuid":protected]=> array(1) { [0]=> string(36) "33f02d5e-56d8-11e8-8464-02f0efebfcdc" } ["_message":"Plivo\Resources\ResponseUpdate":private]=> string(17) "message(s) queued" }

**Comment by algobasket** [comment]
![screenshot from 2018-05-13 23-37-46](https://user-images.githubusercontent.com/8275673/39970313-d5eb7d88-5706-11e8-85ed-481537538bbe.png)

**Comment by cb8** [comment]
```php
$messageUuid = $message_created->getMessageUuid();
```
