### ISSUE TITLE
Error running php plivo app

### ISSUE THREAD

**Issue by luisjaviercr** [plivo/plivo-php#61]
I get this Fatal error: Class 'Plivo\Response' not found in /home/licsy/ivrtugo.licsy.com/IvrFlow.php on line 14,
And one of the Plivo Support agents answer me this: 

Hi ROIBots,

Please check whether you have installed the plivo helper in your directory. 
If not, then the same can be installed using pip by running this command in the terminal from the directory you are working in -  
'sudo pip install plivo'. 
Once the plivo helper is installed the, Class 'Plivo\Response' will be found and you shall not receive the error anymore.

But composer install is all I need to install so my doubt is it is necessary to run pip Plivo install?

Regards,

**Comment by chhedadhaval120386** [comment]
As of the current version I do not face any namespace issues so can you please confirm the version of SDK that you are using?

**Comment by nixonsam** [comment]
@luisjaviercr we are closing this issue. Feel free to reach out to our support team if you need any further assistance or in case of any queries.

**Comment by SoufianAkh** [comment]
I'm having the same issue, while I did install it through Composer.
See screenshot: https://i.imgur.com/xtzZ8iv.png
