### ISSUE TITLE
The SDK messes with the php $_SESSION

### ISSUE THREAD

**Issue by MaartenW** [plivo/plivo-php#71]
Somehow, when using the Plivo\RestClient to send a message, the $_SESSION variable gets messed up. Either the SDK is not using namespace in the $_SESSION or some other tinkering is done.
This conflicted with our authentication system. 
We resorted to using plain `curl_exec`.

I would expect this not to happen.

**Comment by chhedadhaval120386** [comment]
Can you please give some additional details regarding this like 
- Version of the SDK that you are using
- Any particular end point that you were trying

so that I can try and reproduce the issue.

**Comment by MaartenW** [comment]
Sorry. I haven't used the SDK since. I used the latest version of the SDK at July 14th. I tried to send an SMS. Sending an SMS with the SDK somehow prevented PHP to set a $_SESSION variable.
That's all we know...
