### ISSUE TITLE
Problem with plivo/php-sdk 4.1.0

### ISSUE THREAD

**Issue by asterixcapri** [plivo/plivo-php#75]
Hello,
I installed the last version of plivo php-sdk from composer (4.1.0).

When I run the example I receive this error:
`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Plivo\Resources\Call\CallInterface::create(), 3 passed in [...] on line 17 and at least 4 expected in [...]/vendor/plivo/php-sdk/src/Plivo/Resources/Call/CallInterface.php:70`

```
$client = new \Plivo\RestClient($id, $token);

try {
    $response = $client->calls->create(
        $cellular_from,
        ["+39XXXXXXXX"],
        "sms test"
    );
}
catch (\Exception $e) {
    \print_r($e);
}
```
If I downgrade to 4.0.0-beta1 this code works correctly.
Anyone can help me?

Thanks
Alex

**Comment by nixonsam** [comment]
Hey Alex,

Looks like you are trying to send SMS but the resource you are using is 'calls', please use $client->messages->create 

refer https://api-reference.plivo.com/latest/php/resources/message/send-a-message for more info. 

Thank you.

Regards,
Nixon

**Comment by kplaczek** [comment]
@nixonsam this might be true as the third parameter in the create call is 'sms test'. If he does't care about the response this is fine. This is the way calls used to work. (with 3 parameters) This is also the example provided by the readme of this sdk. Now four parameters are required.
 
It has changed some time ago and now fourth paramer is required as it states in the method `create`: `$answerMethod` this needs to be 'GET' or 'POST'. Add 'GET' or 'POST' and this will work as before even is the third parameter the answer url is jiberish.

https://github.com/plivo/plivo-php/blob/master/src/Plivo/Resources/Call/CallInterface.php#L71

**Comment by chhedadhaval120386** [comment]
@asterixcapri unfortunately 4.0.0 live version also has requirement for 4 arguments , 4th one being the request type e.g:- 'GET', 'POST'.

**Comment by nixonsam** [comment]
@asterixcapri we are closing this issue, feel free to contact our support in case of any queries and concerns.
