### ISSUE TITLE
Bad docs

### ISSUE THREAD

**Issue by joyahm** [plivo/plivo-php#85]
```
catch (PlivoRestException $ex) {
    print_r(ex);
}
```
Should be:
```
catch (Plivo\Exceptions\PlivoRestException $ex) {
    print_r($ex);
}
```
some example for reference:
https://api-reference.plivo.com/latest/php/resources/message/send-a-message
https://api-reference.plivo.com/latest/php/resources/message/retrieve-a-message

**Comment by chhedadhaval120386** [comment]
@joyahm Thank you for the solution or we can import this at the top with

`use Plivo\Exceptions\PlivoRestException`

and then in the catch we can reference it like mentioned in the documentation

either ways both options are fine and importing just makes code look that much cleaner

**Comment by nixonsam** [comment]
@joyahm we have updated the docs, closing this issue. Feel free to reach out to our support team in case of any concerns or queries.
